package com.example.dataflow.JdbcSpringCloudSink;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.integration.annotation.ServiceActivator;
import org.springframework.messaging.support.ErrorMessage;

import java.util.function.Consumer;


// Generated by https://start.springboot.io
@Slf4j
@SpringBootApplication
public class JdbcSpringCloudSinkApplication {

	public static void main(String[] args) {
		SpringApplication.run(JdbcSpringCloudSinkApplication.class, args);
	}


}
